### ISSUE TITLE
multiple image fields in backend not supported

### ISSUE THREAD

**Issue by bigsatchmo** [pixx-io/typo3#15]
Plugin: pixxio/pixxio-extension
Version: 2.0.2
TYPO3: 12.4.5

steps to repeat the issue:
1. add a content element with minimum two image fields or add minimum two image fields in page properties (the effect is much better to see in case the image fields are behind different tabs)
2. go to the second image and press "select from pixx.io"
3. the open pixxio select window stick to the first image field and opens behind the tab with the first image field

desired:
possibility to have different image fields in one element and the option to select in more than one different images from pixxio

workaround:
It is possible to select in the first image field one pixxio image after another and safe in between.. the images are saved localy step by step.. after that, the images can be selected in the local file tree in the target pixxio folder without pixxio select window.

thank you

**Comment by rogervanwile** [comment]
Hi @bigsatchmo ,

thanks for your bug report. We fixed the issue right now.

Please upgrade to the latest version of our plugin: 2.0.3

If you notice any other bugs, feel free to create a new issue.

Thanks for your support
