### ISSUE TITLE
pixx.io button not working in inline relation content elements

### ISSUE THREAD

**Issue by tmay-px** [pixx-io/typo3#16]
Plugin: pixxio/pixxio-extension
Version: 2.0.3
TYPO3: 12.4.5

Clicking the "Select from pixx.io"-Button does not work when inside a inline relation, for example a tx_news article with content elements.

The reason seems to be that the event that loads the init() function in ScriptSDK.js is not fired when the IRRE elements are loaded or opened.

**Comment by rogervanwile** [comment]
@tmay-px : Please update to version 2.0.4 of our plugin. This fixes the error.
