### ISSUE TITLE
Scheduler Command: file does not exist

### ISSUE THREAD

**Issue by bigsatchmo** [pixx-io/typo3#18]
Hello pixxio team,

in TYPO3 12 I get an error in the scheduler command like "file does not exist". IMHO in the FilesController.php Line 440 and 464 should look like this:
```
$storage->deleteFile($storage->getFileByIdentifier($file['identifier']));
$storage->replaceFile($storage->getFileByIdentifier($file['identifier']), $absFileIdentifier);
```

thank you
Enrico Kaspar

**Comment by rogervanwile** [comment]
@bigsatchmo : Please update to version 2.0.4 of our plugin. This fixes the error.
