### ISSUE TITLE
Fatal error: Declaration of Pixxio\PixxioExtension\Command\SyncCommand 

### ISSUE THREAD

**Issue by misterboe** [pixx-io/typo3#25]
TYPO3 12; PHP 8.3 

Fatal error: Declaration of Pixxio\PixxioExtension\Command\SyncCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /var/www/html/vendor/pixxio/pixxio-extension/Classes/Command/SyncCommand.php on line 23

**Comment by rogervanwile** [comment]
@misterboe : Thanks for the bugfix. I have just released it in version 2.1.1.
